choose.files()
library(readxl)
library(dplyr)
BDD <- read_excel("C:\\Users\\PC PEO MAX\\Downloads\\recherche_clinique (2).xlsx")
str(BDD)
BDD$Age <- as.numeric(BDD$Age)
BDD$Sexe <- toupper(BDD$Sexe)
BDD$Sexe <- as.factor(BDD$Sexe)
BDD$Suivi_3_mois <- toupper(BDD$Suivi_3_mois)
BDD$Suivi_3_mois <- ifelse(BDD$Suivi_3_mois == "OUI", TRUE, FALSE)
str(BDD)
BDD$IMC <- as.numeric(BDD$IMC)
BDD$Date_Diagnostic <- trimws(BDD$Date_Diagnostic)
BDD$Date_Diagnostic <- as.Date(BDD$Date_Diagnostic, format = "%Y-%m-%d")
str(BDD)
install.packages("tidyr")
library(tidyr)
BDD$Notes <- replace_na(BDD$Notes, "-")
BDD$Age <- replace_na(BDD$Age,0)
BDD <- BDD%>%
  separate_rows(Douleurs,sep = ",")
print(BDD)
install.packages("writexl")
library(writexl)
write_xlsx(BDD, "C:\\Users\\PC PEO MAX\\Downloads\\recherche_clinique (2).xlsx")
print(BDD)
